[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "hova"
version = "1.95"
description = "Hova Language Core"
authors = [
  { name="Xavier" }
]
requires-python = ">=3.10"

[tool.setuptools.packages.find]
where = ["."]
